# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('elevation', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
